### ISSUE TITLE
Module not found: Error: Can't resolve './FileUtils' in Javascript project

### ISSUE THREAD

**Issue by DipanshuJuneja** [gutenye/ocr#19]
I have a vue javascript project inside which I tried installing the module using `npm install @gutenye/ocr-browser` however it gives an error while compiling 
```
error  in ./node_modules/@gutenye/ocr-browser/src/index.ts

Module not found: Error: Can't resolve './FileUtils' in ...
Module not found: Error: Can't resolve './ImageRaw' in 
error  in ./node_modules/@gutenye/ocr-common/src/backend/splitIntoLineImages.ts

Module parse failed: Unexpected token (4:12)
File was processed with these loaders:
 * ./node_modules/vue-cli-plugin-quasar/lib/loader.js.transform-quasar-imports.js
You may need an additional loader to handle the result of these loaders.
| import clipper from 'js-clipper'
| import { ImageRaw } from '#common/backend'
> import type { LineImage, ImageRaw as ImageRawType } from '#common/types'
|
| type pointType = [number, number]

 error  in ./node_modules/@gutenye/ocr-common/src/index.ts

Module parse failed: Unexpected token (8:7)
File was processed with these loaders:
 * ./node_modules/vue-cli-plugin-quasar/lib/loader.js.transform-quasar-imports.js
You may need an additional loader to handle the result of these loaders.
| export * from './backend/FileUtilsBase'
| export * from './backend/ImageRawBase'
> export type * from './types'
```

**Comment by DipanshuJuneja** [comment]
I added Typescript to my project, while the above issue is resolved but I'm seeing this issue

 `Now I'm seeing this error ERROR in ..node_modules\@gutenye\ocr-browser\src\index.ts 
./node_modules/@gutenye/ocr-browser/src/index.ts 7:16-78
[tsl] ERROR in node_modules\@gutenye\ocr-browser\src\index.ts(7,17)
      TS2345: Argument of type '{ FileUtils: typeof FileUtils; ImageRaw: typeof ImageRaw; InferenceSession: InferenceSessionFactory; splitIntoLineImages: (image: ImageRawBase, sourceImage: ImageRawBase) => Promise<LineImage[]>; }' is not assignable to parameter of type '{ FileUtils: FileUtilsBase; ImageRaw: any; InferenceSession: any; splitIntoLineImages: (image: ImageRawBase, sourceImage: ImageRawBase) => Promise<...>; defaultModels: { ...; } | undefined; }'.
  Property 'defaultModels' is missing in type '{ FileUtils: typeof FileUtils; ImageRaw: typeof ImageRaw; InferenceSession: InferenceSessionFactory; splitIntoLineImages: (image: ImageRawBase, sourceImage: ImageRawBase) => Promise<LineImage[]>; }' but required in type '{ FileUtils: FileUtilsBase; ImageRaw: any; InferenceSession: any; splitIntoLineImages: (image: ImageRawBase, sourceImage: ImageRawBase) => Promise<...>; defaultModels: { ...; } | undefined; }'.`

**Comment by gutenye** [comment]
@DipanshuJuneja [When integrating it into the Vue project, you can use the pre-built JavaScript version here, without needing to worry about TypeScript.](https://github.com/gutenye/ocr/blob/7662b2c2dbd2793541920199efd2e21b88a33b20/packages/browser/package.json#L15)

**Comment by gutenye** [comment]
I changed the default exports to prebuilt js [here](https://github.com/gutenye/ocr/pull/20). Can you try the new version 1.4.7?

**Comment by DipanshuJuneja** [comment]
Thanks @gutenye. One question before we close this issue, I'm trying to use a float 16 converted onnx model for faster inference however it accepts a Float32 model. Is that possible? I see this in the error `failed to call OrtRun(). ERROR_CODE: 2, ERROR_MESSAGE: Unexpected input data type. Actual: (tensor(float)) , expected: (tensor(float16))` here is the line I believe ` const input = Float32Array.from(modelData.data);
    return new Tensor("float32", input, [
      1,
      3,
      modelData.height,
      modelData.width,
    ]);`

**Comment by gutenye** [comment]
Try [this](https://github.com/microsoft/onnxruntime/issues/14601#issuecomment-1423005888)
