### ISSUE TITLE
registerBackend onnx InferenceSession  期望暴露/增加 线程配置选项参数接口,或者默认设置为2

### ISSUE THREAD

**Issue by gowy222** [gutenye/ocr#2]
nodejs环境

[ocr](https://github.com/gutenye/ocr/tree/main)/[packages](https://github.com/gutenye/ocr/tree/main/packages)/[common](https://github.com/gutenye/ocr/tree/main/packages/common)/[src](https://github.com/gutenye/ocr/tree/main/packages/common/src)/[backend](https://github.com/gutenye/ocr/tree/main/packages/common/src/backend)
/backend.ts

registerBackend 暴露初始化参数接口，
然后 await Ocr.create() //期望这里可以传入一个json配置项内支持设置线程数,

以前爬过的各种坑...(在web vsIDE 和云函数)
线程数有些情况不能彻底交给onnxruntime托管，尤其是腾讯云AMD 定制的192核心纯cpu环境，不限制线程数，有些时候莫名其妙特别吃内存(docker容器化之后)

**Comment by gutenye** [comment]
Closed in https://github.com/gutenye/ocr/commit/3f22e17eef3463204bade6144202270c548d82ad

[例子](https://github.com/gutenye/ocr/blob/3f22e17eef3463204bade6144202270c548d82ad/packages/node/example/node.ts#L7)

**Comment by gutenye** [comment]
node支持的, 但是是ESM版本, 所以你必须使用"type": "module" in pacakge.json
