### ISSUE TITLE
Question: Can I skip the detection and only go with the recognition?

### ISSUE THREAD

**Issue by DipanshuJuneja** [gutenye/ocr#21]
For my use case, I want to perform inference faster. Can I take the entire resized image as detected area, I suppose if the image contains a lot of text this should have made the inference faster rather than running the recognition model on each detected line? Since on the web for onnxruntime, the inference is too slow!

**Comment by gutenye** [comment]
Hey @DipanshuJuneja, you can fork this project and test the recognition feature by enabling only this line, then review the results. If it works well, I’ll consider implementing it.

One more way to speed it up is by enabling the resize max size to 960 [here](https://github.com/gutenye/ocr/blob/dc7236a6fb73720a46b3ffad0c82df8d57a3f67b/packages/common/src/models/Detection.ts#L23), which should greatly improve the speed. (Depends on the original image size)
