### ISSUE TITLE
[bug] 识别时，第一行文字总是空的

### ISSUE THREAD

**Issue by fanybook** [gutenye/ocr#22]
有个 logo 图片，中英文的，只把英文的识别出来了，但是 eSearch-OCR 把中英文都识别出来了，不过 gutenye-ocr 某些表现又比 eSearch-OCR 要好

我原以为是个别图片，发现不是个例

-----

例图：
这张图片，第一行丢失了 (box 目测正常，但是文字是空)
这张图片，第一行丢失了 (box 目测正常，但是文字是空)
这张图片，第一行丢失了 (box 目测正常，但是文字是空)

![例图](https://gitee.com/fanybook/static/raw/master/WechatIMG20295.jpg)
```js
[
  {
    mean: 0,
    text: '',
    box: [ [ 20, 13 ], [ 926, 13 ], [ 926, 37 ], [ 20, 37 ] ]
  },
  {
    mean: 0.9640309434870015,
    text: "country's entrepreneurs shy away from launches",
    box: [ [ 18, 58 ], [ 676, 57 ], [ 676, 83 ], [ 18, 84 ] ]
  },
  {
    mean: 0.9646686973321773,
    text: 'Aggregate amounts inSbn Companies founded',
    box: [ [ 19, 141 ], [ 761, 141 ], [ 761, 162 ], [ 19, 164 ] ]
  },
  {
    mean: 0.9906626964608828,
    text: 'Dollar-denominated funds',
    box: [ [ 152, 214 ], [ 397, 215 ], [ 397, 236 ], [ 152, 235 ] ]
  },
  {
    mean: 0.9883297142528352,
    text: 'Rmb-denominated funds',
    box: [ [ 159, 241 ], [ 392, 241 ], [ 392, 261 ], [ 159, 261 ] ]
  },
  ... ...
]
```

这张识别手机截图的没事
```js
[
  {
    mean: 0.7437254358378668,
    text: '8:13:52 6 贴 5G 87%',
    box: [ [Array], [Array], [Array], [Array] ]
  },
  {
    mean: 0.9989335983991623,
    text: 'KB/S',
    box: [ [Array], [Array], [Array], [Array] ]
  },
  {
    mean: 0.9960503445731269,
    text: '请认真核对快递单号',
    box: [ [Array], [Array], [Array], [Array] ]
  },
  ... ...
]
```

**Comment by gutenye** [comment]
有很多因素会影响结果, 比如 [01](https://github.com/gutenye/ocr/blob/dc7236a6fb73720a46b3ffad0c82df8d57a3f67b/packages/common/src/models/Detection.ts#L23), [02](https://github.com/gutenye/ocr/blob/dc7236a6fb73720a46b3ffad0c82df8d57a3f67b/packages/common/src/models/Detection.ts#L31-L32), [03](https://github.com/gutenye/ocr/blob/dc7236a6fb73720a46b3ffad0c82df8d57a3f67b/packages/common/src/models/Recognition.ts#L34), [04](https://github.com/gutenye/ocr/blob/dc7236a6fb73720a46b3ffad0c82df8d57a3f67b/packages/common/src/models/Recognition.ts#L41-L42), 自己尝试调整一下参数, 看看结果怎么样

**Comment by gutenye** [comment]
就是[models文件](https://github.com/gutenye/ocr/tree/main/packages/models/assets)大, 如果你自己提供models文件, 可以fork这个repo然后移除@gutenye/ocr-models package. 欢迎提供PR

**Comment by fanybook** [comment]
> 就是[models文件](https://github.com/gutenye/ocr/tree/main/packages/models/assets)大, 如果你自己提供models文件, 可以fork这个repo然后移除@gutenye/ocr-models package. 欢迎提供PR

@gutenye 是我自己搞错了，之前 package.json 开发依赖了 electron，导致我没看见，以为只有 ‘@gutenye/ocr’

看了下，模型只有 16M，最大的是 onnxruntime-node 180+ 这个没办法

**Comment by Bruce-zxy** [comment]
我也遇到了这个情况，在nodejs环境下，第一行文本丢失了
![image](https://github.com/user-attachments/assets/5c0f6e07-a3ab-417d-8ce3-2efa9aaf1dc5)

**Comment by Bruce-zxy** [comment]
在 Demo [https://gutenye-ocr.netlify.app](https://gutenye-ocr.netlify.app) 上识别是没有问题的，我尝试版本降级到1.3.0也会有这个问题。我是在nodejs中指定的.onnx文件来跑的也不行，这些.onnx文件是我直接从Demo上下载下来的

![image](https://github.com/user-attachments/assets/7c8419e6-5737-4f3d-9b62-eeeb9aad4fe4)

![image](https://github.com/user-attachments/assets/4ceed242-e1d0-4fcc-9904-61025d3344ca)

**Comment by fanybook** [comment]
@gutenye

**Comment by gutenye** [comment]
感觉detection阶段有误差, 导致分割出来的图片太小, 一部分文字被截掉了, 导致识别失败. Node下: 用`isDebug`和`debugOutputDir`选项, 可以看到识别过程中产生的各种图片, 检查一下这些图片多不对. [可以看下这个例子](https://github.com/gutenye/ocr/blob/dc7236a6fb73720a46b3ffad0c82df8d57a3f67b/packages/node/example/node-example.ts#L5-L6)

**Comment by fanybook** [comment]
@gutenye 

![debug图](https://gitee.com/fanybook/static/raw/master/boxes-debug-ocr.jpg)

**Comment by Bruce-zxy** [comment]
@gutenye OK，非常感谢！

![image](https://github.com/user-attachments/assets/c3e741a5-f992-4530-b06e-2916bedd688a)
