### ISSUE TITLE
option to specify detection language

### ISSUE THREAD

**Issue by sigmaSd** [gutenye/ocr#6]
like paddleocr `--lang`

**Comment by gutenye** [comment]
You need to download the multi lang models [here](https://github.com/PaddlePaddle/PaddleOCR/blob/main/doc/doc_ch/models_list.md)

Then pass the models in

```
const ocr = await Ocr.create({
  models: {
    detectionPath: '..',
    recognitionPath: '..',
    dictionaryPath: '..'
  }
})
```

**Comment by gutenye** [comment]
(not planned)

auto download like [example](https://github.com/PaddlePaddle/PaddleOCR/blob/502e1675e4acf606214f51f287011990f23f87f5/paddleocr.py#L89)
